// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Account struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type ChatMessage struct {
	ID        int    `json:"id"`
	Author    string `json:"author"`
	Content   string `json:"content"`
	Timestamp string `json:"timestamp"`
}
